@startuml

hide circle
skinparam linetype ortho

entity "Academy.Enrollment" as enrollment
{
    * enrollmentId : varchar(20) <<PK>>
    --
    * grade : numeric
    * section : varchar(2)
}

entity "Accounting.Student" as student
{
    * studentId : varchar(20) <<PK>>
    * enrolmentId : varchar(20) <<FK>>
    --
    * name : varchar(50)
    secondName : varchar(50)
    * surname : varchar(50)
    secondSurname : varchar(50)
    schoolYear : varchar(4)
    tutor : varchar(100)
}

entity "Accounting.Transaction" as transaction
{
    * transactionId : varchar(20) <<PK>> 
    * studentId : varchar(20) <<FK>>
    * cashierId : varchar(20) <<FK>>
    --
    * concept : varchar(200)
    * total : float
    * date : date
    * discount : float
}

entity "Accounting.Cashier" as cashier 
{
    * cashierId : varchar(20) <<PK>>
    --
    * name : varchar(50)
    * surname : varchar(50)
    sex : bool
}

entity "Accounting.Tariff" as tariff
{
    * tariffId : numeric <<generated>>
    --
    concept : varchar(200)
    mount : float
}

entity "Accounting.Tariff_Transaction" as tariffTransaction
{
    * transactionId : varchar(20) <<FK>>
    * tariffId : varchar(20) <<FK>>
}

enrollment ||..o{student
student ||..o{transaction
cashier ||..o{transaction

transaction ||..o{ tariffTransaction
tariff ||..o{ tariffTransaction

@enduml