@startuml

title WSMCBL DataBase

hide circle
skinparam linetype ortho


package Config #LightGray
{
    entity User
    {
        * userId : numeric <<FK>>
        --
        * name : varchar(45)
        secondName : varchar(45)
        * surname : varchar(45)
        secondName : varchar (45)
        * userName : varchar(45)
        * password : varchar(100)
        email : varchar(45)
        * userState : bool
    }

    entity Roles
    {
        * rolId : numeric <<PK>>
        --
        * nameRol : varchar(45)
    }

    entity Permissions
    {
        * permissionsId : numeric <<PK>>
        --
        * namePermission : varchar(45)
    }

    entity Roles_Permissions
    {
        * rolesId : numeric <<FK>>
        --
        * permissionsId : numeric <<FK>>
    }

    entity User_Roles
    {
        userId : numeric <<PK>>
        rolesId : numeric <<PK>>
    }

    User ||..{User_Roles
    Roles ||..{User_Roles
    Roles ||..{Roles_Permissions
    Permissions ||..{Roles_Permissions
}

package Secretary #ff9800
{
    entity Student
    {
        * studentId : varchar(20) <<PK>>
        --
        * name : varchar(50)
        secondName : varchar(50)
        * surname : varchar(50)
        secondSurname : varchar(50)
        * studentState : bool
        * schoolYear : varchar(4)
        tutor : varchar(100)
        * sex : bool
        * birthday : Date
        enrollmentId : varchar(15) <<FK>>
    }

    entity Student_Enrollment
    {
        * id : numeric <<FK>>
        * schoolYear : varchar(4)
        --
        * studentId : varchar(15) <<FK>>
        * enrollmentId : varchar(15) <FK>
    }

    entity Schoolyear
    {
        * schoolyearId : varchar(20) <<PK>>
        --
        * label : varchar(100)
        * startdate : date
        * deadline : date
        isActive : bool
    }

    entity Schoolyear_Student
    {
        * schoolyearId : varchar(20) 
        * studentId : varchar(20)
    }

    Student ||..{ Student_Enrollment
    Student ||..{ Schoolyear_Student
    Schoolyear ||..{ Schoolyear_Student
}

package Accounting #LightBlue
{
    entity Cashier
    {
        * cashierId : varchar(20) <<PK>>
        --
        * userId : numeric <FK>
    }

    entity TariffType
    {
        * typeId : numeric <<generated>>
        --
        * description: varchar(50)
    }

    entity Tariff
    {
        * tariffId : numeric <<generated>>
        * schoolYear : varchar(4)
        --
        * concept : varchar(200)
        * amount : float
        dueDate : datetime
        late : bool
        * typeId : numeric <<FK>>
    }

    entity Tariff_Transaction
    {
        * transactionId : varchar(20) <<FK>>
        * tariffId : varchar(20) <<FK>>
        --
        * amount : float
    }

    entity Transaction
    {
        * transactionId : varchar(20) <<PK>>
        --
        * total : float
        * date : datetime
        * studentId : varchar(20) <<FK>>
        * cashierId : varchar(20) <<FK>>
    }

    entity Discount
    {
        * discountId: smallint <<FK>>
        --
        * description: varchar(200)
        * amount: float
        tag: varchar(50)
    }

    entity Student
    {
        * studentId : varchar(20) <<PK>>
        --
        dicountId : int <<FK>>
    }

    entity DebtHistory
    {
        * studentId : varchar(20) <<FK>>
        * tariffId : int <<FK>>
        --
        * schoolYear : varchar(6)
        * isPaid : bool
        * debtBalance : float
        discount : float
        arrears : float
    }

    Cashier ||..{Transaction
    Tariff ||..{ TariffType
    Tariff ||.up.{ DebtHistory
    Tariff ||..{ Tariff_Transaction
    Student ||.left.{ Transaction
    Student ||..{ Discount
    Student ||.up.{ DebtHistory
    Transaction ||..{ Tariff_Transaction
}

package Academy #LightGreen
{
    entity Enrollment
    {
        * enrollmentId : numeric <<PK>>
        --
        enrollmentLabel : varchar(20)
        * section : varchar(2)
        * shoolYear : varchar(6)
        capacity : numeric
        cuantity : numeric
        * gradeId : varchar(15) <<FK>>
    }

    entity Grade
    {
        *gradeId : varchar(15) <<PK>>
        --
        schoolYear : varchar(6)
    }

    entity Subject
    {
        subjectId : varchar(15) <<PK>>
        --
        name : varchar(100)
        gradeId : varchar(15) <<Fk>>
    }

    entity Teacher
    {
        * teacherId : varchar(15) <<PK>>
        --
        enrollmentId : varchar(20) <<FK>>
        * userId : numeric <<FK>>
    }

    entity Teacher_Enrollment
    {
        * id : varchar(15) <<PK>>
        --
        * teacherId : varchar(15) <<FK>>
        * subjectId : varchar(15) <<FK>>
        * enrollmentId : varchar(20) <<FK>>
    }

    Enrollment }..|| Grade
    Subject }..|| Grade
    Teacher ||..|| Enrollment
    Teacher ||..{ Teacher_Enrollment
    Subject ||..|| Teacher_Enrollment
    Enrollment ||..{ Teacher_Enrollment
}

Secretary.Student ||..|| Accounting.Student
Enrollment ||..{ Student_Enrollment
User ||..|| Cashier
User ||.left.|| Teacher

@enduml