@startuml
scale 4
!theme plain
top to bottom direction
skinparam linetype ortho

class cashier {
   userid: varchar(15)
   cashierid: varchar(15)
}
class debthistory {
   schoolyear: varchar(20)
   subamount: double precision
   arrear: double precision
   amount: double precision
   debtbalance: double precision
   ispaid: boolean
   studentid: varchar(20)
   tariffid: integer
}
class degree {
   label: varchar(25)
   schoolyear: varchar(15)
   educationallevel: varchar(50)
   quantity: integer
   degreeid: varchar(25)
}
class degreecatalog {
   label: varchar(50)
   educationallevel: integer
   degreecatalogid: integer
}
class discount {
   description: varchar(200)
   amount: double precision
   tag: varchar(50)
   discountid: smallint
}
class enrollment {
   degreeid: varchar(25)
   label: varchar(20)
   schoolyear: varchar(20)
   section: varchar(10)
   capacity: smallint
   quantity: smallint
   enrollmentid: varchar(15)
}
class grade {
   studentid: varchar(15)
   subjectid: varchar(15)
   enrollmentid: varchar(15)
   partialid: integer
   grade: double precision
   label: varchar(10)
   gradeid: integer
}
class partial {
   semesterid: integer
   partial: integer
   deadline: date
   label: varchar(20)
   partialid: integer
}
class permission {
   name: varchar(50)
   permissionid: varchar(15)
}
class rol {
   namerol: varchar(50)
   rolid: varchar(15)
}
class rol_permission {
   rolid: varchar(15)
   permissionid: varchar(15)
}
class schoolyear {
   label: varchar(100)
   startdate: date
   deadline: date
   isactive: boolean
   schoolyearid: varchar(15)
}
class schoolyear_student {
   schoolyear: varchar(15)
   studentid: varchar(20)
}
class semester {
   schoolyear: varchar(20)
   semester: integer
   deadline: date
   isactive: boolean
   label: varchar(20)
   semesterid: integer
}
class student {
   discountid: smallint
   educationallevel: smallint
   studentid: varchar(20)
}
class student {
   tutorid: varchar(15)
   name: varchar(50)
   secondname: varchar(50)
   surname: varchar(50)
   secondsurname: varchar(50)
   studentstate: boolean
   sex: boolean
   birthday: date
   diseases: varchar(100)
   religion: varchar(20)
   address: varchar(100)
   studentid: varchar(20)
}
class student {
   schoolyear: varchar(20)
   isapproved: boolean
   studentid: varchar(15)
   enrollmentid: varchar(15)
}
class studentfile {
   studentid: varchar(15)
   transfersheet: boolean
   birthdocument: boolean
   parentidentifier: boolean
   updatedgradereport: boolean
   conductdocument: boolean
   financialsolvency: boolean
   fileid: integer
}
class studentmeasurements {
   studentid: varchar(15)
   weight: double precision
   height: integer
   measurementid: integer
}
class studentparent {
   studentid: varchar(15)
   sex: boolean
   name: varchar(70)
   idcard: varchar(25)
   occupation: varchar(30)
   parentid: varchar(15)
}
class studenttutor {
   name: varchar(70)
   phone: varchar(50)
   tutorid: varchar(15)
}
class subject {
   teacherid: varchar(15)
   subjectid: varchar(15)
   enrollmentid: varchar(15)
}
class subject {
   degreeid: varchar(25)
   name: varchar(100)
   ismandatory: boolean
   semester: integer
   initials: varchar(10)
   subjectid: varchar(15)
}
class subjectcatalog {
   degreecatalogid: integer
   name: varchar(100)
   ismandatory: boolean
   semester: integer
   initials: varchar(10)
   subjectcatalogid: integer
}
class tariff {
   schoolyear: varchar(20)
   educationallevel: smallint
   concept: varchar(200)
   amount: double precision
   duedate: date
   late: boolean
   typeid: integer
   tariffid: integer
}
class tariffcatalog {
   educationallevel: smallint
   concept: varchar(100)
   amount: double precision
   duedate: date
   typeid: integer
   tariffcatalogid: integer
}
class tarifftype {
   description: varchar(50)
   typeid: integer
}
class teacher {
   userid: varchar(15)
   enrollmentid: varchar(20)
   isguide: boolean
   teacherid: varchar(15)
}
class transaction {
   total: double precision
   date: timestamp with time zone
   studentid: varchar(15)
   cashierid: varchar(15)
   transactionid: varchar(20)
}
class transaction_tariff {
   amount: double precision
   transactionid: varchar(15)
   tariffid: integer
}
class user {
   name: varchar(50)
   secondname: varchar(50)
   surname: varchar(50)
   secondsurname: varchar(50)
   username: varchar(45)
   password: varchar(100)
   email: varchar(100)
   userstate: boolean
   userid: varchar(15)
}
class user_rol {
   userid: varchar(15)
   rolid: varchar(15)
}

cashier              -[#595959,plain]-^  user                : "userid"
debthistory          -[#595959,plain]-^  schoolyear          : "schoolyear:schoolyearid"
debthistory          -[#595959,plain]-^  student             : "studentid"
debthistory          -[#595959,plain]-^  tariff              : "tariffid"
degree               -[#595959,plain]-^  schoolyear          : "schoolyear:schoolyearid"
enrollment           -[#595959,plain]-^  degree              : "degreeid"
enrollment           -[#595959,plain]-^  schoolyear          : "schoolyear:schoolyearid"
grade                -[#595959,plain]-^  partial             : "partialid"
grade                -[#595959,plain]-^  student             : "studentid, enrollmentid"
grade                -[#595959,plain]-^  subject             : "subjectid, enrollmentid"
partial              -[#595959,plain]-^  semester            : "semesterid"
schoolyear_student   -[#595959,plain]-^  schoolyear          : "schoolyear:schoolyearid"
schoolyear_student   -[#595959,plain]-^  student             : "studentid"
semester             -[#595959,plain]-^  schoolyear          : "schoolyear:schoolyearid"
student              -[#595959,plain]-^  discount            : "discountid"
student              -[#595959,plain]-^  enrollment          : "enrollmentid"
student              -[#595959,plain]-^  student             : "studentid"
student              -[#595959,plain]-^  student             : "studentid"
student              -[#595959,plain]-^  studenttutor        : "tutorid"
studentfile          -[#595959,plain]-^  student             : "studentid"
studentmeasurements  -[#595959,plain]-^  student             : "studentid"
studentparent        -[#595959,plain]-^  student             : "studentid"
subject              -[#595959,plain]-^  degree              : "degreeid"
subject              -[#595959,plain]-^  enrollment          : "enrollmentid"
subject              -[#595959,plain]-^  subject             : "subjectid"
subject              -[#595959,plain]-^  teacher             : "teacherid"
subjectcatalog       -[#595959,plain]-^  degreecatalog       : "degreecatalogid"
tariff               -[#595959,plain]-^  tarifftype          : "typeid"
teacher              -[#595959,plain]-^  enrollment          : "enrollmentid"
teacher              -[#595959,plain]-^  user                : "userid"
transaction          -[#595959,plain]-^  cashier             : "cashierid"
transaction          -[#595959,plain]-^  student             : "studentid"
transaction_tariff   -[#595959,plain]-^  tariff              : "tariffid"
transaction_tariff   -[#595959,plain]-^  transaction         : "transactionid"
user_rol             -[#595959,plain]-^  rol                 : "rolid"
user_rol             -[#595959,plain]-^  user                : "userid"
@enduml
