@startuml
skinparam BackgroundColor transparent

Views ..> Controllers
Views .right.> Models
Controllers ..> Models

package Views
{
    class CollectTariffView <<View>>
    class PreEnrollmentView <<View>>
    class ViewNotesOnlineView <<View>>

    class ClassView <<View>>
    class TariffView <<View>>
    class SubjectView <<View>>
    class EnrollmentView <<View>>
    class  <<View>>

    class StudentProfileView <<View>>
    class TeacherView <<View>>
    class PrincipalView <<View>>
    class DeputyPrincipalView <<View>>
    class SecretaryView <<View>>
    class CashierView <<View>>
    class AdministratorView <<View>>
    class PastorView <<View>>

    'class <<View>>
    class View <<View>>
}

package Controllers
{
    class class2 <<Controller>>
}

package Models
{
    class class3 <<Model>>
}

@enduml