@startuml
'skinparam BackgroundColor transparent
hide circle
hide empty methods

Views ..> Models
Controllers ..> Models
Views ..> Controllers

package Models
{
    Management ..> Accounting
    Management ..> Secretary
    Secretary ..> Academy
    Accounting ..> Academy
}


newpage
package Views
{
    class CollectTariffView <<View>>
    class EnrollStudentView <<View>>
    class ViewNotesOnlineView <<View>>

    class GradeView <<View>>
    class GradesView <<View>>
    class SubjectView <<View>>
    class SubjectsView <<View>>
    class TariffView <<View>>
    class FinishTariffView <<View>>
    class EnrollmentView <<View>>
    class EnrollmentsView <<View>>
    class EvangelizedStudentsView <<View>>

    class StudentProfileView <<View>>
    class StudentProfilesView <<View>>
    class TeacherView <<View>>
    class PrincipalView <<View>>
    class DeputyPrincipalView <<View>>
    class SecretaryView <<View>>
    class CashierView <<View>>
    class AdministratorView <<View>>
    class PastorView <<View>>

    class View <<View>>
    class LoginView <<View>>
    class RegisterView <<View>>
}


newpage
package Controllers
{
    class EnrollStudentController <<Controller>>
    class CollectTariffController <<Controller>>
    class CreateOfficialEnrollmentController <<Controller>>
    class MoveTeacherGuideFromEnrollmentController <<Controller>>
    class PrintingReceiptsController <<Controller>>
    class PrintDocumentsController <<Controller>>
    class PrintReportCardController
    class CreateProfileStudentController <<Controller>>
    class LogoutController <<Controller>>

    PrintDocumentsController <|-- PrintingReceiptsController
    PrintDocumentsController <|-- PrintReportCardController
}






newpage
class Models.StudentEntity <<Model>>
class Models.SesionEntity <<Model>>

namespace Models.Academy{
    class NoteEntity <<Model>>
    class StudentEntity <<Model>>
    class TeacherEntity <<Model>>
    class SubjectEntity <<Model>>
    class EnrollmentEntity <<Model>>


    class SubjectEntities <<Model>>
    class StudentEntities <<Model>>
    class TeacherEntities <<Model>>

    Models.StudentEntity <|-- StudentEntity

    SubjectEntities o--> SubjectEntity
    StudentEntities o--> StudentEntity
        
    TeacherEntity *--> SubjectEntity
    TeacherEntities o--> TeacherEntity

    EnrollmentEntity "1" --* "*" StudentEntity
    EnrollmentEntity "1" *--> "1" TeacherEntity

    SubjectEntity *--> NoteEntity
    NoteEntity --> StudentEntity
}


namespace Models.Secretary{
    class GradeEntity <<Model>>
    class ReportEntity <<Model>>
    class GradeEntities <<Model>>
    class TeacherEntity <<Model>>
    class StudentEntities <<Model>>
    class TeacherEntities <<Model>>
    class SecretaryEntity <<Model>>
    class EnrollmentEntity <<Model>>

    SecretaryEntity ..> GradeEntity
    GradeEntity "*" *-- "*" EnrollmentEntity
    GradeEntity *--> SubjectEntity
    GradeEntities *-- GradeEntity
    SecretaryEntity ..> ReportEntity
    SecretaryEntity ..> Models.Academy.StudentEntity
    SecretaryEntity ..> TeacherEntity
}

namespace Models.Management{
    class PrincipalEntity <<Model>>
    class DeputyPrincipalEntity <<Model>>
    class PastorEntity <<Model>>
    class CalendarEntity <<Model>>
    class ReportEntity <<Model>>
    
    Models.Academy.TeacherEntity <|-- PastorEntity
    DeputyPrincipalEntity --> CalendarEntity
    PrincipalEntity ..> ReportEntity
}
    
namespace Models.Accounting{
    class ReportEntity <<Model>>
    class StudentEntity <<Model>>
    class CashierEntity <<Model>>
    class TariffEntities <<Model>>
    class StudentEntities <<Model>>
    class TransactionEntity <<Model>>
    class AccountingBoxEntity <<Model>>

    Models.StudentEntity <|-- Models.Accounting.StudentEntity

    CashierEntity --> AccountingBoxEntity
    CashierEntity --> TransactionEntity
    AccountingBoxEntity --* TransactionEntity
    StudentEntity --* TransactionEntity
}
'class AdministratorEntity <<Model>>

'--- Relations ---
Models.Academy.EnrollmentEntity --> Models.Secretary.EnrollmentEntity
Models.Secretary.GradeEntity "*" *-- "*" Models.Academy.EnrollmentEntity

@enduml