@startuml
left to right direction

actor Secretary

boundary EnrollmentView

control CreateEnrollmentController

entity EnrollmentEntity
entity EnrollmentEntities
entity SubjectEntities
entity SubjectEntity
entity TeacherEntities
entity TeacherEntity


'--- Actor relations ---
Secretary --> EnrollmentView

'--- Views relations ---
EnrollmentView --> CreateEnrollmentController

'--- Controllers relations ---
CreateEnrollmentController --> EnrollmentEntity
CreateEnrollmentController --> EnrollmentEntities
CreateEnrollmentController --> TeacherEntities
CreateEnrollmentController --> SubjectEntities

'--- Entity relations ---
EnrollmentEntity --> TeacherEntity
EnrollmentEntity --> SubjectEntity

TeacherEntities ..> TeacherEntity
SubjectEntities ..> SubjectEntity
@enduml