@startuml

left to right direction
'allow_mixing

actor Foo1
boundary Foo2
boundary Foo55
control Foo3
entity Foo4

Foo1 --> Foo2 : get(use id)
Foo1 --> Foo55 : update()

Foo2 --> Foo3
Foo55 --> Foo3

Foo3 --> Foo4

@enduml