@startuml

class CollectTariffController{

    + applyArreas() : void
    + applyDiscount(float discount) : void
    + createTransaction() : void
    + getStudent() : StudentEntity
    + setStudentId(int idStudent) : void
    + getStudentList() : List<StudentEntity>
    + saveTransaction(TransactionEntity transaction) : void


    + printTransaction() : void
    + printStateAccount() : void


    + isArreas() : bool
    + getDollarRate() : float
    + isPaymentDollars() : bool
    + computeChange(float amount) : void
}

CollectTariffView --> CollectTariffController
StudentProfilesView --> CollectTariffController

CollectTariffController ..> StudentEntities
CollectTariffController ..> TransactionEntity
CollectTariffController ..> PrintDocumentsController


newpage

class EnrollStudentController{
    + saveEnroll() : void
    + isEnrollSave() : bool
    + getStudentList() : List<StudentEntity>
    + getStudent(int idStudent) : StudentEntity
    + getGradesInformation() : List<GradeEntity>
    + setStudent(StudentEntity student) : void
    + setEnrollment(GradeEntity grade, int enrollment) : void
    + printEnrollDocument(StudentEntity student, string enrollmentId) : void
}

StudentProfilesView --> EnrollStudentController
EnrollView --> EnrollStudentController

EnrollStudentController o--> StudentEntity
EnrollStudentController --> StudentEntities
EnrollStudentController --> GradeEntities
EnrollStudentController --> GradeEntity
EnrollStudentController --> PrintDocumentsController


newpage

class CreateOfficialEnrollmentController{
    + getListGrades(int schoolYear) : List<GradeEntity>
    + setGrade(GradeEntity grade) : void
    + updateGrade() : void


    + setQuantitySection(int quantity) : void
    + searchSubject(string subject) : List<subjectEntity>
    + removeSubject(string subjectId) : void
    + setTeacherGuide(TeacherEntity teacher) : void
    + assignTeacher(TeacherEntity teacher, SubjectEntity subject : void


    + print(GradeEntity grade) : void
}

GradesView --> CreateOfficialEnrollmentController
CreateEnrolmentsView --> CreateOfficialEnrollmentController

CreateOfficialEnrollmentController --> TeacherEntities
CreateOfficialEnrollmentController ..> PrintDocumentsController
CreateOfficialEnrollmentController --> GradeEntities
CreateOfficialEnrollmentController ..> SubjectEntity
CreateOfficialEnrollmentController ..> TeacherEntity
CreateOfficialEnrollmentController ..> GradeEntity

newpage

class PrintingReceiptsController {
    - transaction : TransactionEntity
    + print() : Void
    + getData(int transactionId) : TransactionEntity
}

FinishTariffView --> PrintingReceiptsController
PrintingReceiptsController o--> TransactionEntity


newpage
class MoveTeacherGuideFromEnrollmentController {
    + getListTeacher() : List<TeacherEntity>
    + setTeacherGuide(TeacherEntity teacher) : void
}

EnrollmentView --> MoveTeacherGuideFromEnrollmentController
MoveTeacherGuideFromEnrollmentController --> TeacherEntity
MoveTeacherGuideFromEnrollmentController --> TeacherEntities

newpage
class PrintReportCardController {
    - partials : List<int> 
    + print() : void
    + setPartials(List<int> partials) : void
    + getStudent() : StudentEntity  
}

ReportCardView --> PrintReportCardController

PrintReportCardController --> StudentEntity
PrintReportCardController --> EnrollmentEntity
PrintReportCardController --> TimeEntity
@enduml