@startwbs

* Sistema web
** Calificaciones online
** Inicio
*** Dashboard
*** Accesos rápido
** Contabilidad
*** Cobrar
*** Reportes
**** Aplicar mora
**** Debitar
** Académico
*** Estudiantes
*** Profesores
*** Reportes
** Secretaría
*** Estudiantes
*** Matrícula
*** Reportes
** Configuración
*** Usuarios
*** Taza de cambio

@endwb