@startuml
left to right direction

'--- Classes definition ---
actor "Secretary\nand Cashier" as theActor

boundary CreateProfileView

control CreateStudentProfileController

entity StudentEntity
entity StudentEntities
entity TutorEntity
entity TutorEntities
entity DebtHistoryEntities
entity Accounting.StudentEntities

'--- Actor relations ---
theActor --> CreateProfileView

'--- Views relations ---
CreateProfileView --> CreateStudentProfileController

'--- Controllers relations ---
CreateStudentProfileController --> StudentEntities
CreateStudentProfileController --> TutorEntities
CreateStudentProfileController --> DebtHistoryEntities
CreateStudentProfileController --> Accounting.StudentEntities

'--- Entity relations ---
StudentEntities --> StudentEntity
TutorEntities --> TutorEntity
Accounting.StudentEntities ..> StudentEntity

@enduml