@startuml
left to right direction

actor Secretary

boundary EnrollmentView

control MoveTeacherFromSubjectController

entity EnrollmentEntities



'--- Actor relations ---
Secretary --> EnrollmentView

'--- Views relations ---
EnrollmentView --> MoveTeacherFromSubjectController

'--- Controllers relations ---
MoveTeacherFromSubjectController --> EnrollmentEntities

'--- Entity relations ---
@enduml