@startuml
left to right direction

actor Secretary

boundary EnrollmentView

control MoveTeacherFromSubjectController

entity EnrollmentEntities


'--- Actor relations ---
Secretary --> EnrollmentView
note on link
    some()
end note

'--- Views relations ---
EnrollmentView --> MoveTeacherFromSubjectController
note on link
    update()
end note

'--- Controllers relations ---
MoveTeacherFromSubjectController --> EnrollmentEntities

'--- Entity relations ---

@enduml