@startuml
left to right direction

actor Administrador

boundary UserListView
boundary CreateUserView

control CreateUserController

entity UserEntities
entity UserEntity
entity PermissionEntities
entity PermissionEntity
entity RoleEntities
entity RoleEntity


'--- Actor relations ---
Administrador --> UserListView
Administrador --> CreateUserView

'--- Views relations ---
UserListView --> CreateUserView
UserListView --> CreateUserController
CreateUserView --> CreateUserController

'--- Controllers relations ---
CreateUserController --> UserEntities
CreateUserController --> UserEntity
CreateUserController --> PermissionEntities
CreateUserController --> RoleEntities

'--- Entity relations ---
RoleEntities ..> RoleEntity
PermissionEntities ..> PermissionEntity
UserEntities ..> UserEntity

UserEntity --> RoleEntity
UserEntity --> PermissionEntity
@enduml