@startuml
left to right direction

actor Administrator

boundary UserListView
boundary CreateUserView

control CreateUserController

entity UserEntities
entity UserEntity
entity RoleEntities
entity RoleEntity
entity PermissionEntities
entity PermissionEntity

'--- Actor relations ---
Administrator --> UserListView
note on link
    seeUserList()
    createUser()
end note

Administrator --> CreateUserView
note on link
    seeRoleList()
    selectRole()
    seePermissionList()
    selectPermissions()
    save()
end note

'--- Views relations ---
UserListView --> CreateUserView : init()
UserListView --> CreateUserController : getUserList()

rectangle CU as ": AssignRolAndPermissions"
UserListView --> CU

CreateUserView --> CreateUserController
note on link
    getRoleList()
    getPermissionList()
    createUser(user =)
end note

'--- Controllers relations ---
CreateUserController --> PermissionEntities : getList()
CreateUserController --> RoleEntities : getList()
CreateUserController --> UserEntities
note on link
    getList()
    create(user =)
end note
CreateUserController --> UserEntity : init(roleId =)
CreateUserController --> CreateUserController
note on link
    createEmailAccount(username, password)
    createNextcloudAccount(username, password)
end note

'--- Entity relations ---
PermissionEntities ..> PermissionEntity
RoleEntities ..> RoleEntity
UserEntities ..> UserEntity

UserEntity --> RoleEntity : getId()
UserEntity --> PermissionEntity : getId()

@enduml