@startuml
package Views
package Controllers

package Models{
    package Management
    package Accounting
    package Secretary
    package Academy

    Management ..> Accounting
    Management ..> Secretary
    Secretary ..> Academy
    Accounting ..> Academy
}

Views ..> Models
Controllers ..> Models
Views ..> Controllers


newpage
package Views{
    boundary CollectTariffView
    boundary EnrollStudentView
    boundary ViewNotesOnlineView

    boundary GradeView
    boundary GradesView
    boundary SubjectView
    boundary SubjectsView
    boundary TariffView 
    boundary FinishTariffView
    boundary EnrollmentView
    boundary EnrollmentsView
    boundary EvangelizedStudentsView

    boundary StudentView
    boundary StudentsView
    boundary TeacherView
    boundary PrincipalView
    boundary DeputyPrincipalView
    boundary SecretaryView
    boundary CashierView
    boundary AdministratorView
    boundary PastorView

    boundary View
    boundary LoginView


'////////////////////////////////////////////////////////////

    LoginView <|-- View

    View <|-- CashierView
    View <|-- SecretaryView
    View <|-- PrincipalView
    View <|-- TeacherView
    View <|-- AdministratorView
    View <|-- PastorView
    View <|-- DeputyPrincipalView


    CashierView --> StudentsView
    StudentsView --> StudentView
    StudentsView --> CollectTariffView
    CollectTariffView --> TariffView
    TariffView --> FinishTariffView

    SecretaryView --> StudentProfilesView
    StudentProfilesView --> EnrollStudentView

    SecretaryView --> GradesView
    GradesView --> GradeView
    GradeView --> EnrollmentsView
    EnrollmentsView --> EnrollmentView

    GradeView --> SubjectsView
    SubjectsView --> SubjectView

    PastorView --> EvangelizedStudentsView

    StudentView --> ViewNotesOnlineView
}


newpage

package Controllers{
    control EnrollStudentController
    control CollectTariffController
    control CreateOfficialEnrollmentController
    control MoveTeacherGuideFromEnrollmentController
    control PrintingReceiptsController
    control PrintDocumentsController
    control PrintReportCardController
    control CreateProfileStudentController
    control LogoutController

    PrintDocumentsController <|-- PrintingReceiptsController
    PrintDocumentsController <|-- PrintReportCardController
}


newpage
package Models{

package Other{
    entity Other.StudentEntity as "StudentEntity"
    'entity SessionEntity <<Model>>
    'entity AdministratorEntity <<Model>>
}

package Academy{
    entity Academy.NoteEntity as "NoteEntity"
    entity Academy.StudentEntity as "StudentEntity"
    entity Academy.TeacherEntity as "TeacherEntity"
    entity Academy.SubjectEntity as "SubjectEntity"
    entity Academy.EnrollmentEntity as "EnrollmentEntity"
    entity Academy.PastorEntity as "PastorEntity"

    entity Academy.SubjectEntities as "SubjectEntities"
    entity Academy.StudentEntities as "StudentEntities"
    entity Academy.TeacherEntities as "TeacherEntities"

    Academy.StudentEntity --> Other.StudentEntity

    Academy.SubjectEntities o--> Academy.SubjectEntity
    Academy.StudentEntities o--> Academy.StudentEntity
        
    Academy.TeacherEntity *--> Academy.SubjectEntity
    Academy.TeacherEntities o--> Academy.TeacherEntity

    Academy.EnrollmentEntity "1" --* "*" Academy.StudentEntity
    Academy.EnrollmentEntity "1" *--> "1" Academy.TeacherEntity

    Academy.SubjectEntity *--> Academy.NoteEntity
    Academy.NoteEntity --> Academy.StudentEntity


    Academy.TeacherEntity <|-- Academy.PastorEntity
}

package Secretary{
    entity Secretary.GradeEntity as "GradeEntity"
    entity Secretary.ReportEntity as "ReportEntity"
    entity Secretary.StudentEntity as "StudentEntity"
    entity Secretary.TeacherEntity as "TeacherEntity"
    entity Secretary.SecretaryEntity as "SecretaryEntity"
    entity Secretary.EnrollmentEntity as "EnrollmentEntity"
    entity Secretary.GradeEntities as "GradeEntities"
    entity Secretary.StudentEntities as "StudentEntities"
    entity Secretary.TeacherEntities as "TeacherEntities"

    Secretary.StudentEntity --> Other.StudentEntity

    Secretary.GradeEntity "*" *-- "*" Secretary.EnrollmentEntity
    Secretary.GradeEntity *--> Academy.SubjectEntity
    Secretary.GradeEntities *-- Secretary.GradeEntity
    Secretary.SecretaryEntity ..> Secretary.StudentEntity
    Secretary.SecretaryEntity ..> Secretary.GradeEntity
    Secretary.SecretaryEntity ..> Secretary.ReportEntity
    Secretary.SecretaryEntity ..> Secretary.TeacherEntity

    Secretary.StudentEntities ..> Secretary.StudentEntity
    Secretary.TeacherEntities ..> Secretary.TeacherEntity

    Secretary.TeacherEntity ..> Secretary.GradeEntity
}

package Management{
    entity Management.ReportEntity as "ReportEntity"
    entity Management.CalendarEntity as "CalendarEntity"
    entity Management.PrincipalEntity as "PrincipalEntity"
    entity Management.DeputyPrincipalEntity as "DeputyPrincipalEntity"
    
    Management.DeputyPrincipalEntity --> Management.CalendarEntity
    Management.PrincipalEntity ..> Management.ReportEntity
    Management.PrincipalEntity ..> Management.CalendarEntity
}
    
package Accounting{
    entity Accounting.ReportEntity as "ReportEntity"
    entity Accounting.StudentEntity as "StudentEntity"
    entity Accounting.CashierEntity as "CashierEntity"
    entity Accounting.TariffEntities as "TariffEntities"
    entity Accounting.StudentEntities as "StudentEntities"
    entity Accounting.TransactionEntity as "TransactionEntity"
    entity Accounting.AccountingBoxEntity as "AccountingBoxEntity"

    Accounting.StudentEntity --> Other.StudentEntity

    Accounting.CashierEntity --> Accounting.AccountingBoxEntity
    Accounting.CashierEntity --> Accounting.TransactionEntity
    Accounting.CashierEntity --> Accounting.ReportEntity
    Accounting.CashierEntity --> Accounting.TariffEntities
    Accounting.CashierEntity --> Accounting.StudentEntities

    Accounting.StudentEntities ..> Accounting.StudentEntity
    Accounting.AccountingBoxEntity --* Accounting.TransactionEntity
    Accounting.StudentEntity --* Accounting.TransactionEntity
}

Academy.EnrollmentEntity --> Secretary.EnrollmentEntity

}
@enduml