@startuml
package Views
package Controllers

package Models{
    package Management
    package Accounting
    package Secretary
    package Academy

    Management ..> Accounting
    Management ..> Secretary
    Secretary ..> Academy
    Accounting ..> Academy
}

Views ..> Models
Controllers ..> Models
Views ..> Controllers


newpage
package Views{
    boundary CollectTariffView
    boundary EnrollStudentView
    boundary ViewNotesOnlineView

    boundary GradeView
    boundary GradesView
    boundary SubjectView
    boundary SubjectsView
    boundary TariffView 
    boundary FinishTariffView
    boundary EnrollmentView
    boundary EnrollmentsView
    boundary EvangelizedStudentsView

    boundary StudentView
    boundary StudentsView
    boundary TeacherView
    boundary PrincipalView
    boundary DeputyPrincipalView
    boundary SecretaryView
    boundary CashierView
    boundary AdministratorView
    boundary PastorView

    boundary View
    boundary LoginView


'////////////////////////////////////////////////////////////

    LoginView <|-- View

    View <|-- CashierView
    View <|-- SecretaryView
    View <|-- PrincipalView
    View <|-- TeacherView
    View <|-- AdministratorView
    View <|-- PastorView
    View <|-- DeputyPrincipalView


    CashierView --> StudentsView
    StudentsView --> StudentView
    StudentsView --> CollectTariffView
    CollectTariffView --> TariffView
    TariffView --> FinishTariffView

    SecretaryView --> StudentProfilesView
    StudentProfilesView --> EnrollStudentView

    SecretaryView --> GradesView
    GradesView --> GradeView
    GradeView --> EnrollmentsView
    EnrollmentsView --> EnrollmentView

    GradeView --> SubjectsView
    SubjectsView --> SubjectView

    PastorView --> EvangelizedStudentsView

    StudentView --> ViewNotesOnlineView


}


newpage

package Controllers{
    entity EnrollStudentController <<Controller>>
    entity CollectTariffController <<Controller>>
    entity CreateOfficialEnrollmentController <<Controller>>
    entity MoveTeacherGuideFromEnrollmentController <<Controller>>
    entity PrintingReceiptsController <<Controller>>
    entity PrintDocumentsController <<Controller>>
    entity PrintReportCardController
    entity CreateProfileStudentController <<Controller>>
    entity LogoutController <<Controller>>

    PrintDocumentsController <|-- PrintingReceiptsController
    PrintDocumentsController <|-- PrintReportCardController
}


newpage
package Models{

package Other{
    entity o.StudentEntity as "StudentEntity" <<Model>>
    'entity SessionEntity <<Model>>
    'entity AdministratorEntity <<Model>>
}

package Academy{
    entity NoteEntity <<Model>>
    entity StudentEntity <<Model>>
    entity TeacherEntity <<Model>>
    entity SubjectEntity <<Model>>
    entity EnrollmentEntity <<Model>>

    entity SubjectEntities <<Model>>
    entity StudentEntities <<Model>>
    entity TeacherEntities <<Model>>

    StudentEntity --> o.StudentEntity

    SubjectEntities o--> SubjectEntity
    StudentEntities o--> StudentEntity
        
    TeacherEntity *--> SubjectEntity
    TeacherEntities o--> TeacherEntity

    EnrollmentEntity "1" --* "*" StudentEntity
    EnrollmentEntity "1" *--> "1" TeacherEntity
    EnrollmentEntity --> Secretary.EnrollmentEntity

    SubjectEntity *--> NoteEntity
    NoteEntity --> StudentEntity
}

package Secretary{
    entity GradeEntity <<Model>>
    entity ReportEntity <<Model>>
    entity StudentEntity1
    entity TeacherEntity <<Model>>
    entity SecretaryEntity <<Model>>
    entity EnrollmentEntity1
    entity GradeEntities <<Model>>
    entity StudentEntities <<Model>>
    entity TeacherEntities <<Model>>

    StudentEntity --> o.StudentEntity

    GradeEntity "*" *-- "*" EnrollmentEntity
    GradeEntity *--> SubjectEntity
    GradeEntities *-- GradeEntity
    SecretaryEntity ..> StudentEntity
    SecretaryEntity ..> GradeEntity
    SecretaryEntity ..> ReportEntity
    SecretaryEntity ..> TeacherEntity

    StudentEntities ..> StudentEntity
    TeacherEntities ..> TeacherEntity
}

package Management{
    entity PastorEntity <<Model>>
    entity ReportEntity <<Model>>
    entity CalendarEntity <<Model>>
    entity PrincipalEntity <<Model>>
    entity DeputyPrincipalEntity <<Model>>
    
    Models.Academy.TeacherEntity <|-- PastorEntity
    DeputyPrincipalEntity --> CalendarEntity
    PrincipalEntity ..> ReportEntity
    PrincipalEntity ..> CalendarEntity
}
    
package Accounting{
    entity ReportEntity <<Model>>
    entity StudentEntity <<Model>>
    entity CashierEntity <<Model>>
    entity TariffEntities <<Model>>
    entity StudentEntities <<Model>>
    entity TransactionEntity <<Model>>
    entity AccountingBoxEntity <<Model>>

    StudentEntity --> StudentEntity

    CashierEntity --> AccountingBoxEntity
    CashierEntity --> TransactionEntity
    AccountingBoxEntity --* TransactionEntity
    StudentEntity --* TransactionEntity
}

}
@enduml