@startuml
left to right direction

'--- Classes definition ---
actor Secretary

boundary ReportCardView

control PrintReportCardController

entity ProfileStudentController

'note on link
'end note

'--- Actor relations ---

'--- Views relations ---

'--- Controllers relations ---

'--- Entity relations ---
@enduml