@startuml
left to right direction

actor Cashier

boundary CollectTariffView
boundary StudentProfilesView

control CollectTariffController
control CreateProfileStudentController

entity ProfileStudentEntity
entity ProfileStudentEntites
entity TransactionEntity
entity CashierEntity


Cashier --> CollectTariffView
Cashier --> StudentProfilesView

CollectTariffView --> CollectTariffController
StudentProfilesView --> CollectTariffController
StudentProfilesView --> CreateProfileStudentController

CollectTariffController --> ProfileStudentEntites
CollectTariffController --> ProfileStudentEntity
CollectTariffController --> TransactionEntity
CollectTariffController --> CashierEntity

ProfileStudentEntity --> TransactionEntity
CashierEntity --> ProfileStudentEntity
ProfileStudentEntites --> ProfileStudentEntity
@enduml