@startuml
left to right direction

actor Cashier

boundary CollectTariffView
boundary StudentProfilesView

control CollectTariffController
control CreateProfileStudentController
control PrintDocumentsController

entity ProfileStudentEntity
entity ProfileStudentEntites
entity TransactionEntity
entity CashierEntity


Cashier --> CollectTariffView
Cashier --> StudentProfilesView

CollectTariffView --> CollectTariffController
StudentProfilesView --> CollectTariffController
StudentProfilesView --> CreateProfileStudentController

CollectTariffController --> ProfileStudentEntites
CollectTariffController --> ProfileStudentEntity
CollectTariffController --> TransactionEntity
CollectTariffController --> CashierEntity
CollectTariffController --> PrintDocumentsController
CreateProfileStudentController --> ProfileStudentEntites

ProfileStudentEntity --> TransactionEntity
CashierEntity --> TransactionEntity
@enduml