@startuml
left to right direction

actor Cashier

boundary CollectTariffView
boundary StudentsView

control CollectTariffController
control CreateStudentController
control PrintDocumentsController

entity StudentEntity
entity StudentEntites
entity TransactionEntity
entity CashierEntity



'--- Actor relations ---
Cashier --> CollectTariffView
Cashier --> StudentsView

'--- Views relations ---
CollectTariffView --> CollectTariffController
StudentsView --> CollectTariffController
StudentsView --> CreateStudentController

'--- Controllers relations ---
CollectTariffController --> StudentEntites
CollectTariffController --> TransactionEntity
CollectTariffController -left-> PrintDocumentsController

CreateStudentController --> StudentEntites
PrintDocumentsController --> TransactionEntity

'--- Entity relations ---
TransactionEntity --> CashierEntity
TransactionEntity --> StudentEntity

@enduml