@startuml
skinparam BackgroundColor transparent

:User: as "Generic User"

User <|-- Administrator
User <|-- Director
User <|-- Subdirector
User <|-- Secretary
User <|-- Cashier
User <|-- Profesor


Profesor <|-- Pastor

:Time: as "Time"
:Customer: as Customer

@enduml