@startuml
'skinparam BackgroundColor transparent
footer Los casos de uso con (*) no han sido desarrollados ni están en desarrollo.


state Initial as "HOME"
state OPEN_ENROLLMENT_VIEW
state OPEN_PROFILES_VIEW
state OPEN_PROFILE
state OPEN_TARIFFS_VIEW


'-- Relations --
[*] --> Initial : Start system (*)

Initial --> OPEN_PROFILES_VIEW : Show Profiles (*)
Initial --> OPEN_ENROLLMENT_VIEW
note on link
    Enroll student
    Show Enrollments (*)
    CreateOfficialEnrollmentBySection
end note

OPEN_ENROLLMENT_VIEW --> OPEN_PROFILE : Show Profile (*)
OPEN_ENROLLMENT_VIEW --> OPEN_ENROLLMENT_VIEW : MoveTeacherGuideFromEnrollment

OPEN_PROFILES_VIEW --> OPEN_PROFILE : Show Profile (*)
OPEN_PROFILES_VIEW --> OPEN_TARIFFS_VIEW : CollectTariffs

OPEN_PROFILE --> OPEN_PROFILE : PrintReportCardByStudent

OPEN_TARIFFS_VIEW --> OPEN_TARIFFS_VIEW : Printing\nInvoicesAndReceipts


Initial --> [*] : Close system (*)
OPEN_ENROLLMENT_VIEW --> [*] : Close system (*)
OPEN_PROFILES_VIEW --> [*] : Close system (*)
OPEN_PROFILE --> [*] : Close system (*)
OPEN_TARIFFS_VIEW --> [*] : Close system (*)
@enduml