@startuml
skinparam BackgroundColor transparent

component "Iteration 1" as Iteration1

note bottom of Iteration1: Se consideró que dicho casos de usos\n eran parte fundamental del negocio y se le dio prioridad.

usecase PreEnrollment
usecase CreateOfficialEnrollmentBySection
usecase PrintingInvoicesAndReceipts
usecase PrintReportCardByStudent
usecase MoveTeacherGuideFromEnrollment
usecase CollectTariffs

Iteration1 -> PreEnrollment
Iteration1 -> CreateOfficialEnrollmentBySection
Iteration1 -> PrintingInvoicesAndReceipts
Iteration1 -> PrintReportCardByStudent
Iteration1 -> MoveTeacherGuideFromEnrollment
Iteration1 -> CollectTariffs


@enduml