@startuml
'skinparam BackgroundColor transparent
left to right direction

rectangle "Iteration 1" as Iteration1

note top of Iteration1: Se consideró que dichos casos de usos eran parte\nfundamental del negocio y se les dió prioridad.\nLos cuales coincidieron con los riesgo considerados.

usecase CU01 as "EnrollStudent"
usecase CU05 as "CreateOfficialEnrollmentBySection"
usecase CU58 as "PrintingInvoicesAndReceipts"
usecase CU29 as "PrintReportCardByStudent"
usecase CU21 as "MoveTeacherGuideFromEnrollment"
usecase CU03 as "CollectTariffs"

Iteration1 .. CU01 : CU01
Iteration1 .. CU05 : CU05
Iteration1 .. CU58 : CU58
Iteration1 .. CU29 : CU29
Iteration1 .. CU21 : CU21
Iteration1 .. CU03 : CU03
@enduml