@startuml
left to right direction
title Iteration 1

label RF01 as "RF01. Cobro de aranceles."
label RF02 as "RF02. Matricular estudiante."
label RF06 as "RF06. Creación de matrícula oficial por grado."
label RF12 as "RF12. Gestionar matrículas."
label RF14 as "RF14. Imprimir boleta de calificación por secciones."

label 0 as " "
0 ..[hidden]> RF01
0 ..[hidden]> RF02
0 ..[hidden]> RF06
0 ..[hidden]> RF12
0 ..[hidden]> RF14

newpage
left to right direction
title Iteration 2
label 0 as " "

Label RF10 as "RF10. Gestionar perfiles de estudiantes."
Label RF24 as "RF24. Gestionar usuarios del sistema."
Label RF03 as "RF03. Gestionar las calificaciones."
Label RF33 as "RF33. Abonos a pago de un arancel."

0 ..[hidden]> RF10
0 ..[hidden]> RF24
0 ..[hidden]> RF03
0 ..[hidden]> RF33


newpage
left to right direction
title Iteration 3
label 0 as " "

Label RF04 as "RF04. Generar informes administrativos."
label RF06 as "RF06. Creación de Matrícula Oficial por grado"
Label RF07 as "RF07. Ver calificaciones online."
Label RF08 as "RF08. Ver historial de pagos por estudiante."
Label RF10 as "RF10. Gestionar perfiles de estudiantes."
Label RF12 as "RF12. Gestionar matrículas."
Label RF31 as "RF31. Impresión de facturas y recibos."
Label RF36 as "RF36. Generar estadísticas de ingresos."

0 ..[hidden]> RF04
0 ..[hidden]> RF06
0 ..[hidden]> RF07
0 ..[hidden]> RF08
0 ..[hidden]> RF10
0 ..[hidden]> RF12
0 ..[hidden]> RF31
0 ..[hidden]> RF36


newpage
left to right direction
title Iteration 4
label 0 as " "

label RF06 as "RF06. Creación de Matrícula Oficial por grado"
Label RF09 as "RF09. Generar informe de deudores."
Label RF10 as "RF10. Gestionar perfiles de estudiantes."
Label RF12 as "RF12. Gestionar matrículas."
Label RF24 as "RF24. Gestionar usuarios del sistema."
Label RF33 as "RF33. Abonos a pago de un arancel."
Label RF34 as "RF34. Habilitar el registro de notas por corte evaluativo."

0 ..[hidden]> RF06
0 ..[hidden]> RF09
0 ..[hidden]> RF10
0 ..[hidden]> RF12
0 ..[hidden]> RF24
0 ..[hidden]> RF33
0 ..[hidden]> RF34


newpage
left to right direction
title Iteration 5
label 0 as " "

Label RF01 as "RF01. Cobro de aranceles."
Label RF04 as "RF04. Generar informes administrativos."
Label RF12 as "RF12. Gestionar matrículas."
Label RF18 as "RF18. Generar informe de rendimientos por secciones."
Label RF24 as "RF24. Gestionar usuarios del sistema."
Label RF29 as "RF29. Ver panel de información desempeño."
Label RF37 as "RF37. Gestionar años lectivos."
Label RF38 as "RF38. Generar copias de seguridad."

0 ..[hidden]> RF01
0 ..[hidden]> RF04
0 ..[hidden]> RF12
0 ..[hidden]> RF18
0 ..[hidden]> RF24
0 ..[hidden]> RF29
0 ..[hidden]> RF37
0 ..[hidden]> RF38


newpage
left to right direction
title Iteration 6
label 0 as " "

Label RF10 as "RF10. Gestionar perfiles de estudiantes."
label RF12 as "RF12. Gestionar matrículas."
Label RF17 as "RF17. Generar datos estadísticos por corto evaluativo."
Label RF18 as "RF18. Generar informe de rendimientos por secciones."
Label RF24 as "RF24. Gestionar usuarios del sistema."

0 ..[hidden]> RF10
0 ..[hidden]> RF12
0 ..[hidden]> RF17
0 ..[hidden]> RF18
0 ..[hidden]> RF24

@enduml