@startuml
'skinparam BackgroundColor transparent
left to right direction


label RF01 as "RF01. Cobro de aranceles"
label RF02 as "RF02. Matricular estudiante"
label RF06 as "RF06. Creación de Matrícula Oficial por grado"
label RF12 as "RF12. Gestionar matrículas"
label RF14 as "RF14. Imprimir boleta de calificación por secciones"

label 0 as " "
0 ..[hidden]> RF01
0 ..[hidden]> RF02
0 ..[hidden]> RF06
0 ..[hidden]> RF12
0 ..[hidden]> RF14


title Iteration 2

Label RF10 as "RF10. Gestionar perfiles de estudiantes."
Label RF24 as "RF24. Gestionar usuarios del sistema."
Label RF03 as "RF03. Gestionar las calificaciones."
Label RF07 as "RF07. Ver calificaciones online."
Label RF33 as "RF33. Abonos a pago de un arancel."

0 ..[hidden]> RF10
0 ..[hidden]> RF24
0 ..[hidden]> RF03
0 ..[hidden]> RF07
0 ..[hidden]> RF33

@enduml