@startuml
'skinparam BackgroundColor transparent
left to right direction
scale 2

'Iteration 1
Label RF01 as "RF01. Cobro de aranceles"
Label RF02 as "RF02. Matricular estudiante"
label RF06 as "RF06. Creación de Matrícula Oficial por grado"
label RF12 as "RF12. Gestionar matrículas"
label RF14 as "RF14. Imprimir boleta de calificación por secciones"

'Iteration 2
Label RF10 as "RF10. Gestionar perfiles de estudiantes."
Label RF24 as "RF24. Gestionar usuarios del sistema."
Label RF03 as "RF03. Gestionar las calificaciones."
Label RF33 as "RF33. Abonos a pago de un arancel."

'Iteration 3
Label RF04 as "RF04. Generar informes administrativos."
Label RF07 as "RF07. Ver calificaciones online."
Label RF08 as "RF08. Ver historial de pagos por estudiante."
Label RF31 as "RF31. Impresión de facturas y recibos."
Label RF36 as "RF36. Generar estadísticas de ingresos."

'Iteration 4
Label RF09 as "RF09. Generar informe de deudores."
Label RF34 as "RF34. Habilitar el registro de notas por corte evaluativo."


'Iteration 1
usecase CU01 as "EnrollStudent"
usecase CU05 as "UpdateOfficialEnrollmentBySection"
usecase CU58 as "PrintingInvoicesAndReceipts"
usecase CU29 as "PrintReportCardByStudent"
usecase CU21 as "MoveTeacherGuideFromEnrollment"
usecase CU03 as "CollectTariffs"

'Iteration 2
usecase CU60 as "PayTariff"
usecase CU11 as "AddStudentGrade"
usecase CU02 as "CreateStudentProfile"
usecase CU69 as "Login"

'Iteration 3
usecase CU15 as "ViewGradeOnline"
usecase CU16 as "UpdateStudentProfile"
usecase CU22 as "MoveTeacherFromSubject"
usecase CU23 as "MoveStudentFromEnrollment"
usecase CU73 as "CancelTransaction"
usecase CU75 as "TransactionReportByDate"

'Iteration 4
usecase CU07 as "GenerateDebtorReport"
usecase CU20 as "CreateEnrollment"
usecase CU46 as "CreateUser"
usecase CU51 as "ViewUserProfile"
usecase CU61 as "EnablePartialGradeRecording"
usecase CU71 as "AssignRolAndPermissions"
usecase CU77 as "CorrectEducationalLevel"
usecase CU78 as "ForgetDebt"



'Iteration 1
RF01 ..> CU03 : trace
RF01 ..> CU58 : trace
RF02 ..> CU01 : trace
RF06 ..> CU05 : trace
RF12 ..> CU05 : trace
RF12 ..> CU21 : trace
RF14 ..> CU29 : trace

'Iteration 2
RF01 ..> CU60 : trace
RF06 ..> CU22 : trace
RF10 ..> CU02 : trace
RF10 ..> CU69 : trace
RF24 ..> CU69 : trace
RF33 ..> CU60 : trace
RF03 ..> CU11 : trace
RF07 ..> CU15 : trace

'Iteration 3
RF08 ..> CU75 : trace
RF04 ..> CU75 : trace
RF36 ..> CU75 : trace
RF31 ..> CU73 : trace
RF31 ..> CU58 : trace
RF10 ..> CU16 : trace
RF12 ..> CU23 : trace

'Iteration 4
RF09 ..> CU07 : trace
RF06 ..> CU20 : trace
RF12 ..> CU20 : trace
RF24 ..> CU46 : trace
RF24 ..> CU51 : trace
RF34 ..> CU61 : trace
RF24 ..> CU71 : trace
RF10 ..> CU77 : trace
RF33 ..> CU78 : trace
@enduml