@startuml
'skinparam BackgroundColor transparent
left to right direction


frame MU01 <<MU01>> as "Tariff colletion"
frame MU02 <<MU02>> as "Finish collection"
frame MU03 <<MU03>> as "Collection of multiple tariffs"
frame MU04 <<MU04>> as "Print report card by student"
frame MU05 <<MU05>> as "Enrollment View"
frame MU06 <<MU06>> as "Update enrollment information"
frame MU07 <<MU07>> as "Tariff profiles"
frame MU08 <<MU08>> as "Enroll student.\n    Main view"
frame MU09 <<MU09>> as "\t\tEnroll student.\nAdministrative information tab"
frame MU10 <<MU10>> as "Student profiles"

rectangle Initial as "HOME"
rectangle OPEN_ENROLLMENT_VIEW
rectangle OPEN_PROFILES_VIEW
rectangle OPEN_PROFILE
rectangle OPEN_TARIFFS_VIEW


MU01 .up.> OPEN_PROFILES_VIEW
MU01 .up.> OPEN_TARIFFS_VIEW

MU02 .up.> OPEN_TARIFFS_VIEW

MU03 .up.> OPEN_TARIFFS_VIEW

MU04 .up.> OPEN_ENROLLMENT_VIEW

MU05 .down.> Initial
MU05 .up.> OPEN_ENROLLMENT_VIEW
MU05 ..> OPEN_PROFILE

MU06 .up.> OPEN_ENROLLMENT_VIEW
MU06 ..> OPEN_PROFILE

MU07 ..> Initial
MU07 ..> OPEN_PROFILES_VIEW

MU08 ..> OPEN_ENROLLMENT_VIEW
MU08 ..> OPEN_PROFILES_VIEW

MU09 ..> OPEN_ENROLLMENT_VIEW
MU09 ..> OPEN_PROFILES_VIEW

MU10 ..> OPEN_PROFILES_VIEW
@enduml