@startuml
skinparam BackgroundColor transparent


frame MU04 <<MU04>> as "Print report card by student"
frame MU05 <<MU05>> as "Enrollment View"
frame MU06 <<MU06>> as "Update enrollment information"

rectangle Initial as "HOME"
rectangle s1 as "OPEN_ENROLLMENT_VIEW"
rectangle s3 as "OPEN_PROFILE"


MU04 .up.> s1

MU05 .up.> Initial
MU05 .up.> s1
MU05 ..> s3

MU06 .up.> s1
MU06 ..> s3


@enduml