@startuml
skinparam BackgroundColor transparent
left to right direction

label RF01 as "RF01. Cobro de aranceles"
label RF02 as "RF02. Prematricular estudiante"
label RF06 as "RF06. Creación de Matrícula Oficial por grado"
label RF12 as "RF12. Gestionar matrículas"
label RF14 as "RF14. Imprimir boleta de calificación por secciones"

usecase CU01 as "PreEnrollment"
usecase CU05 as "CreateOfficialEnrollmentBySection"
usecase CU58 as "PrintingInvoicesAndReceipts"
usecase CU29 as "PrintReportCardByStudent"
usecase CU21 as "MoveTeacherGuideFromEnrollment"
usecase CU03 as "CollectTariffs"

RF01 ..> CU03 : trace
RF01 ..> CU58 : trace
RF02 ..> CU01 : trace
RF06 ..> CU05 : trace
RF12 ..> CU05 : trace
RF12 ..> CU21 : trace
RF14 ..> CU29 : trace

@enduml

