@startuml
'skinparam BackgroundColor transparent
scale 2
left to right direction


' Primera iteración
actor User
actor Secretary
actor Cashier

User <|-- Secretary
User <|-- Cashier

usecase EnrollStudent
usecase CreateOfficialEnrollmentBySection
usecase PrintingInvoicesAndReceipts
usecase PrintReportCardByStudent
usecase MoveTeacherGuideFromEnrollment
usecase CollectTariffs

Secretary --> EnrollStudent
Secretary --> CreateOfficialEnrollmentBySection
Secretary --> PrintReportCardByStudent
Secretary --> MoveTeacherGuideFromEnrollment

Cashier --> CollectTariffs

CollectTariffs ..> PrintingInvoicesAndReceipts: include


' Primera iteración
actor Client
actor Teacher

User <|-- Teacher

usecase CU15 as "ViewGradeOnline"
usecase CU60 as "PayTariff"
usecase CU22 as "MoveTeacher"
usecase CU11 as "AddStudentGrade"
usecase CU02 as "CreateStudentProfile"
usecase CU69 as "Login"
usecase "Logout*"

User -left-> CU69
User -right-> "Logout*"

Secretary --> CU22
Secretary --> CU02

Cashier --> CU02
Cashier --> CU60

Teacher --> CU11

Client --> CU15

@enduml