@startuml
scale 2
left to right direction


'Iteration 1
actor User
actor Secretary
actor Cashier

User <|-- Secretary
User <|-- Cashier

usecase EnrollStudent
usecase CreateOfficialEnrollmentBySection
usecase PrintingInvoicesAndReceipts
usecase PrintReportCardByStudent
usecase MoveTeacherGuideFromEnrollment
usecase CollectTariffs

Secretary --> EnrollStudent
Secretary --> CreateOfficialEnrollmentBySection
Secretary --> PrintReportCardByStudent
Secretary --> MoveTeacherGuideFromEnrollment

Cashier --> CollectTariffs

CollectTariffs ..> PrintingInvoicesAndReceipts: include
CreateOfficialEnrollmentBySection ..> MoveTeacherGuideFromEnrollment : include

'Iteration 2
actor Client
actor Teacher

User <|-- Teacher

usecase CU60 as "PayTariff"
usecase CU11 as "AddStudentGrade"
usecase CU02 as "CreateStudentProfile"
usecase CU69 as "Login"
usecase "Logout*"

User -left-> CU69
User -right-> "Logout*"

Secretary --> CU02

Cashier --> CU02

Teacher --> CU11

CollectTariffs ..> CU60 : include


'Iteration 3
usecase CU15 as "ViewGradeOnline"
usecase CU16 as "UpdateStudentProfile"
usecase CU22 as "MoveTeacherFromSubject"
usecase CU23 as "MoveStudentFromEnrollment"
usecase CU73 as "CancelTransaction"
usecase CU75 as "TransactionReportByDate"


Client --> CU15

Secretary --> CU16
Secretary --> CU22
Secretary --> CU23

Cashier --> CU73
Cashier --> CU75

Admin --> CU75

CreateOfficialEnrollmentBySection ..> CU22 : include

CU16 ..> CU23 : include

@enduml