@startuml
scale 2
left to right direction


'Iteration 1
actor User
actor Secretary
actor Cashier

User <|-- Secretary
User <|-- Cashier

usecase EnrollStudent
usecase CU05 as "UpdateOfficialEnrollmentBySection"
usecase PrintingInvoicesAndReceipts
usecase PrintReportCardByStudent
usecase CU21 as "MoveTeacherGuideFromEnrollment"
usecase CU03 as "CollectTariffs"

Secretary --> EnrollStudent
Secretary --> CU05
Secretary --> PrintReportCardByStudent
Secretary --> CU21

Cashier --> CU03

CU03 ..> PrintingInvoicesAndReceipts: include

'Iteration 2
actor Customer
actor Teacher

User <|-- Teacher

usecase CU60 as "PayTariff"
usecase CU11 as "AddStudentGrade"
usecase CU02 as "CreateStudentProfile"
usecase CU69 as "Login"
usecase "Logout*"

User -left-> CU69
User -right-> "Logout*"

Secretary --> CU02

Cashier --> CU02

Teacher --> CU11

CU03 ..> CU60 : include


'Iteration 3
actor Administrator

User <|-- Administrator

usecase CU15 as "ViewGradeOnline"
usecase CU16 as "UpdateStudentProfile"
usecase CU22 as "MoveTeacherFromSubject"
usecase CU23 as "MoveStudentFromEnrollment"
usecase CU73 as "CancelTransaction"
usecase CU75 as "TransactionReportByDate"


Customer --> CU15

Secretary --> CU16
Secretary --> CU22
Secretary --> CU23

Cashier --> CU73
Cashier --> CU75

Administrator --> CU75


CU16 ..> CU23 : include


'Iteration 4
actor Principal

User <|-- Principal

usecase CU07 as "GenerateDebtorReport"
usecase CU20 as "CreateEnrollment"
usecase CU46 as "CreateUser"
usecase CU51 as "ViewUserProfile"
usecase CU61 as "EnablePartialGradeRecording"
usecase CU71 as "AssignRolAndPermissions"
usecase CU77 as "CorrectEducationalLevelOfTheProfile"
usecase CU78 as "ForgetDebt"

Principal --> CU07
Principal --> CU61

Secretary --> CU20
Secretary --> CU77

Administrator --> CU46
Administrator --> CU61
Administrator --> CU71

Cashier --> CU77
Cashier --> CU78

User -left-> CU51

CU05 ..> CU21 : include
CU05 ..> CU22 : include

'Iteration 4

@enduml