@startuml
left to right direction

actor Cashier

boundary TransactionListView

control CancelTransactionController

entity TransactionEntities
entity TransactionEntity


'--- Actor relations ---
Cashier --> TransactionListView

'--- Views relations ---
TransactionListView --> CancelTransactionController

'--- Controllers relations ---
CancelTransactionController --> TransactionEntities
CancelTransactionController --> TransactionEntity

'--- Entity relations ---
@enduml