@startuml
left to right direction

actor Cashier

boundary TransactionListView

control CancelTransactionController

entity TransactionEntities
entity TransactionEntity


'--- Actor relations ---
Cashier --> TransactionListView
note on link
    seeTransactionList()
    cancelTransaction(id = )
end note

'--- Views relations ---
TransactionListView --> CancelTransactionController
note on link
    getTransactionList()
    cancelTransaction(transactionId = )
end note

'--- Controllers relations ---
CancelTransactionController --> TransactionEntities : getAll()
CancelTransactionController --> TransactionEntity
note on link
    isValid = false
end note

'--- Entity relations ---

@enduml