@startuml

title Generic UseCase Analysis

package analysis {
    boundary xView
    control xController
    entity xEntity
    entity xDAO

    xView --> xController
    xController ..> xEntity
    xController ..> xDAO
}

package front{
    boundary "xView - Blazor" as xViewF
    boundary "xView - Blazor" as xViewF
    control "xController - Blazro" as xControllerF
    entity "xEntity - Blazor" as xEntity1
    entity "xDAO - Blazor" as xDAO1

    xViewF --> xControllerF
    xControllerF ..> xEntity1
    xControllerF ..> xDAO1
}

package back{
    boundary "xView - C#" as xViewB
    control "xController - C#" as xControllerB
    entity "xEntity - C#" as xEntity2
    entity "xDAO - C#" as xDAO2

    xViewB --> xControllerB
    xControllerB ..> xEntity2
    xControllerB ..> xDAO2
}
@enduml