@startuml

left to right direction
node Client
node WebClient
node WebServer
node Server
node DataBaseServer

Client <|-right- WebClient
Client -- WebServer : https
WebServer -- Server : https
Server -- DataBaseServer : EF Core


newpage

package Deploy{
    node Client
    node WebClient
    node WebServer
    node Server
    node DataBaseServer

    Client <|-- WebClient
    Client -right- WebServer : https
    WebServer -right- Server : https
    Server -right- DataBaseServer : EF Core
}

component browser as "browser"
component api as "API wsmcbl.back.dll" <<server>>
component database as "Data Base" <<server>>
component web as "Web wsmcbl.front.dll" <<Server>>

WebClient *--> browser
WebServer *--> web
Server *--> api
DataBaseServer *--> database

browser .right.> web : <<use>>
web .right.> api : <<use>>
api .right.> database : <<use>>

@enduml