@startuml

left to right direction
node Client
node webClient
node webServer

Client <|-right- webClient
Client -- webServer : https

newpage

package Deploy{
    node Client
    node webClient
    node webServer

    Client <|-down- webClient
    Client -right- webServer : https
}

component c.browser as "browser"
component api.wsmcbl as "API wsmcbl"
component c.dataBaseServer as "dataBaseServer"
component c.webServer as "webServer"

webServer *--> c.webServer
webClient *--> c.browser
webServer *--> api.wsmcbl
webServer *--> c.dataBaseServer

c.browser ..> c.webServer : <<use>>
c.webServer .right.> api.wsmcbl : <<use>>
api.wsmcbl .right.> c.dataBaseServer : <<use>>

@enduml