@startuml
left to right direction

actor Secretary

boundary GradesView
boundary CreateEnrolmentsView

control CreateOfficialEnrollmentController
control PrintDocumentsController

entity EnrollmentEntity
entity StudentEntites
entity TeacherEntity
entity GradeEntity
entity SubjectEntities
entity TeacherEntities


'--- Actor relations ---
Secretary --> GradesView
Secretary --> CreateEnrolmentsView


'--- Views relations ---
GradesView --> CreateOfficialEnrollmentController
CreateEnrolmentsView --> CreateOfficialEnrollmentController


'--- Controllers relations ---
CreateOfficialEnrollmentController --> GradeEntity
CreateOfficialEnrollmentController --> TeacherEntities
CreateOfficialEnrollmentController --> PrintDocumentsController

PrintDocumentsController --> EnrollmentEntity


'--- Entities relations ---
GradeEntity --> SubjectEntities
GradeEntity "1" --> "n" EnrollmentEntity
GradeEntity --> StudentEntites

EnrollmentEntity "1" --> "1" TeacherEntity
@enduml
