@startuml
left to right direction

actor Secretary

boundary TransactionReportView

control TransactionReportByDateController

entity TransactionEntities


'--- Actor relations ---
Secretary --> TransactionReportView
note on link
    selectReport()
    seeReport()
end note

'--- Views relations ---
TransactionReportView --> TransactionReportByDateController
note on link
    getReportByDate(range=)
    getTariffTypeList()
end note

'--- Controllers relations ---
TransactionReportByDateController --> TransactionEntities
note on link
    getTransactionList(range=)
    getTariffTypeList()
    getUsername()
    getSummary()
end note

'--- Entity relations ---

@enduml