@startuml
left to right direction

actor Secretary

boundary EnrollmentView

control UpdateEnrollmentController

entity EnrollmentEntity
entity EnrollmentEntities
entity SubjectEntities
entity SubjectEntity
entity TeacherEntities
entity TeacherEntity


'--- Actor relations ---
Secretary --> EnrollmentView

'--- Views relations ---
EnrollmentView --> UpdateEnrollmentController

'--- Controllers relations ---
UpdateEnrollmentController --> EnrollmentEntity
UpdateEnrollmentController --> EnrollmentEntities
UpdateEnrollmentController --> TeacherEntities
UpdateEnrollmentController --> SubjectEntities

'--- Entity relations ---
EnrollmentEntity --> TeacherEntity
EnrollmentEntity --> SubjectEntity

TeacherEntities ..> TeacherEntity
SubjectEntities ..> SubjectEntity
@enduml