@startuml
left to right direction

actor Secretary

boundary EnrollmentView

control UpdateEnrollmentController

entity EnrollmentEntities
entity TeacherEntities
entity SubjectEntities
entity EnrollmentEntity
entity TeacherEntity
entity SubjectEntity

'--- Actor relations ---
Secretary --> EnrollmentView
note on link
    selectTeacher()
    updateInformation()
    changeTeacherGuide()
    seeInformation()
    seeStudentList()
end note

'--- Views relations ---
EnrollmentView --> UpdateEnrollmentController
note on link
    getEnrollmentById(id=)
    updateEnrollment(enrollment=)
end note

'--- Controllers relations ---
UpdateEnrollmentController --> EnrollmentEntities : getById(id = )
UpdateEnrollmentController --> SubjectEntities : getByEnrollmentId(id =)
UpdateEnrollmentController --> TeacherEntities : getById(id = )

'--- Entity relations ---
TeacherEntities ..> TeacherEntity : getId()
SubjectEntities ..> SubjectEntity : getByEnrollmentId(id =)

EnrollmentEntity --> TeacherEntity
note on link
    getId()
    forgetEnrollment()
end note
EnrollmentEntity --> SubjectEntity : updateTeacher(id =)
@enduml