@startwbs
'skinparam BackgroundColor transparent

* Iglesia Bautista Libertad \n\t Propietarios
** Director
***< Caja
*** Sub-Director
****< Secretaria
**** Profesores
***** Alumnos
****< \tPersonal de\nlimpieza y Seguridad
** Capellan

@endwb