@startuml
left to right direction

'--- Classes definition ---
actor Secretary

boundary StudentsView
boundary EnrollView

control EnrollStudentController
control PrintDocumentsController

entity StudentEntity
entity StudentEntities
entity EnrollmentEntity
entity GradeEntities
entity GradeEntity

rectangle ":collaboration PrintDocument*" as printDocument
rectangle ":collaboration CreateProfileStudent" as createProfileStudent


'--- Actor relations ---
Secretary --> StudentsView
Secretary --> EnrollView

'--- Views relations ---
StudentsView --> EnrollStudentController
StudentsView --> createProfileStudent
EnrollView --> EnrollStudentController

'--- Controllers relations ---
EnrollStudentController --> StudentEntities
EnrollStudentController --> GradeEntities
EnrollStudentController --> GradeEntity

EnrollStudentController -right-> PrintDocumentsController

PrintDocumentsController --> printDocument

'--- Entity relations ---
EnrollmentEntity --> StudentEntity
GradeEntities --> GradeEntity
GradeEntity --> EnrollmentEntity
GradeEntity --> StudentEntity

@enduml