@startuml
left to right direction

'--- Classes definition ---
actor Secretary

boundary StudentsView
boundary EnrollView

control EnrollStudentController
control PrintDocumentsController

entity StudentEntity
entity StudentEntities
entity EnrollmentEntity
entity GradeEntities
entity GradeEntity

rectangle ":collaboration PrintDocument*" as printDocument
rectangle ":collaboration CreateProfileStudent" as createProfileStudent


'--- Actor relations ---
Secretary --> StudentsView
note on link
    openStudent()
    createStudent()
    searchStudent()
end note

Secretary --> EnrollView
note on link
    setStudentInformation()
    setEnrollment()
    saveEnroll()
    printEnroll()
    cancel()
end note


'--- Views relations ---
StudentsView --> EnrollStudentController
note on link
    getStudentList()
    getStudent(studentId="")
    setStudent(student = " ")
end note

StudentsView --> createProfileStudent

EnrollView --> EnrollStudentController
note on link
    setProfileInformation()
    isEnrollSave()
    printEnrollDocument(enroll="")
    saveEnroll()
    getGradesInformation()
    setEnrollment(grade, section)
end note

'--- Controllers relations ---
EnrollStudentController --> StudentEntities
note on link
    geStudenttList()
    geStudent(profile=" ")
end note

EnrollStudentController --> GradeEntities
note on link
    getGradesList()
    getEnrollment(enrollmentId = "")
end note

EnrollStudentController --> GradeEntity
note on link
    addStudent(student = " ", section)
    isStudentRepeating()
end note

EnrollStudentController -right-> PrintDocumentsController
note on link
    printInformation(data)
end note

PrintDocumentsController --> printDocument


'--- Entity relations ---
EnrollmentEntity -> StudentEntity
note on link
    getProfileId()
end note

GradeEntities -> GradeEntity
note on link
    getGradeId()
end note

GradeEntity --> EnrollmentEntity
note on link
    getLabel()
    getRemainingSpace()
    enrollStudent(student = " ")
end note

GradeEntity --> StudentEntity
note on link
    getStudentId()
    getEnrollmentInformation()
end note

@enduml