@startuml
left to right direction

actor "Cashier/Principal"

boundary ReportView

control GenerateDebtorReportController

entity Academy.StudentEntities
entity DebtHistoryEntities
entity DocumentMaker

'--- Actor relations ---
"Cashier/Principal" --> ReportView
note on link
    seeTransactionList()
    cancelTransaction(id = )
end note

'--- Views relations ---
ReportView --> GenerateDebtorReportController
note on link
    getTransactionList()
    cancelTransaction(transactionId = )
end note

'--- Controllers relations ---
GenerateDebtorReportController --> DocumentMaker
GenerateDebtorReportController --> Academy.StudentEntities : getAll()
GenerateDebtorReportController --> DebtHistoryEntities
note on link
    isValid = false
end note

'--- Entity relations ---
DocumentMaker --> Academy.StudentEntities

@enduml