@startuml
left to right direction

actor Secretary

boundary GradesView
boundary CreateEnrolmentsView

control UpdateOfficialEnrollmentController
control PrintDocumentsController

entity EnrollmentEntity
entity StudentEntities
entity TeacherEntity
entity GradeEntity
entity SubjectEntities
entity TeacherEntities


'--- Actor relations ---
Secretary --> GradesView
Secretary --> CreateEnrolmentsView


'--- Views relations ---
GradesView --> UpdateOfficialEnrollmentController
CreateEnrolmentsView --> UpdateOfficialEnrollmentController


'--- Controllers relations ---
UpdateOfficialEnrollmentController --> GradeEntity
UpdateOfficialEnrollmentController --> TeacherEntities
UpdateOfficialEnrollmentController --> PrintDocumentsController

PrintDocumentsController --> EnrollmentEntity


'--- Entities relations ---
GradeEntity --> SubjectEntities
GradeEntity "1" --> "n" EnrollmentEntity
GradeEntity --> StudentEntities

EnrollmentEntity "1" --> "1" TeacherEntity
@enduml
