@startuml
left to right direction

actor Secretary

boundary GradesView
boundary CreateEnrolmentsView

control UpdateOfficialEnrollmentController
control PrintDocumentsController
rectangle SubjectCatalog as ":collaboration SubjectCatalog*"
rectangle Print as ":collaboration PrintDocument*"
rectangle Update as ":collaboration UpdateInformationGrade*"

entity EnrollmentEntity
entity StudentEntities
entity TeacherEntity
entity GradeEntity
entity GradeEntities
entity SubjectEntities
entity TeacherEntities 


'--- Actor relations ---
Secretary --> GradesView
note on link
    openGrades()
end note

Secretary --> CreateEnrolmentsView
note on link
    saveEnrolment()
    addTeacher()
    assignTeacher()
    searchSubject()
    openSubjectCatalog()
    removeSubject()
    updateQuantitySection()
end note


'--- Views relations ---
GradesView --> UpdateOfficialEnrollmentController
note on link
    getListGrades()
    setGrade(schoolYear)
    updateInformationGrade()
end note

GradesView --> Update

CreateEnrolmentsView --> UpdateOfficialEnrollmentController
note on link
    setQuantitySection(int quantitySection)
    searchSubject(Subject)
    removeSubject(Subject)
    setTeacherGuide(Teacher)
    assignTeacher(Teacher,Subject)
end note

CreateEnrolmentsView --> SubjectCatalog


'--- Controllers relations ---
UpdateOfficialEnrollmentController --> GradeEntity
note on link
    createEnrollments(int quantity)
    addSubjects(Subject)
    removeSubject(Subject)
    save()
end note

UpdateOfficialEnrollmentController --> TeacherEntities
note on link
    getListTeacher()
end note

UpdateOfficialEnrollmentController --> PrintDocumentsController
note on link
    printiInformationData()
end note

UpdateOfficialEnrollmentController --> GradeEntities
note on link
    getListGrade()
end note

PrintDocumentsController --> Print


'--- Entities relations ---
GradeEntity --> SubjectEntities
note on link
    getListSubject()
    getSubject()
end note

GradeEntity "1" --> "n" EnrollmentEntity
note on link
    construct(schoolYear, label, list<subject>)
    getLabel()
    setCapacityEnrollment(int Capacity)
    setTeacherGuide(Teacher)
    assignTeacher(Teacher,Subject)
    getStudentList()
end note

GradeEntity --> StudentEntities
note on link
    getListStudent()
end note

EnrollmentEntity "1" --> "1" TeacherEntity
note on link
    addSubject(subject="")
end note

@enduml